(function(){var d=void 0,g=true,i=null,j=false;function k(){return function(){}}function n(a){return function(){return this[a]}}function o(a){return function(){return a}}var p,q=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b,c){return a.call.apply(a.bind,arguments)}function ca(a,b,c){if(!a)throw Error();if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function r(a,b,c){r=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ba:ca;return r.apply(i,arguments)}function da(a){var b=ea;function c(){}c.prototype=b.prototype;a.W=b.prototype;a.prototype=new c;a.prototype.constructor=a};function fa(a,b){var c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}function ga(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function ha(a,b){var c="",e=ia(encodeURIComponent(a));e.splice(b||5,e.length);s(e,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",e;a>0;)e=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(e)+b,a>>>=6;a=b}c+=a});return c}
function ia(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,e=4023233417,f=2562383102,h=271733878,m=3285377520,y=[],l,F,J,N,Q,P=Math.ceil((a.length/4+2)/16),S=[P],O=0,K;O<P;O++){S[O]=[];for(l=0;l<16;l++)S[O][l]=a.charCodeAt(O*64+l*4)<<24|a.charCodeAt(O*64+l*4+1)<<16|a.charCodeAt(O*64+l*4+2)<<8|a.charCodeAt(O*64+l*4+3)}O=(a.length-1)*8;a=P-1;S[a][14]=Math.floor(O/Math.pow(2,32));S[a][15]=O&4294967295;for(O=0;O<P;O++){for(K=0;K<16;K++)y[K]=S[O][K];
for(K=16;K<80;K++)y[K]=(y[K-3]^y[K-8]^y[K-14]^y[K-16])<<1|(y[K-3]^y[K-8]^y[K-14]^y[K-16])>>>31;a=c;l=e;F=f;J=h;N=m;for(K=0;K<80;K++)Q=Math.floor(K/20),Q=(a<<5|a>>>27)+(Q==0?l&F^~l&J:Q==1?l^F^J:Q==2?l&F^l&J^F&J:l^F^J)+N+b[Q]+y[K]&4294967295,N=J,J=F,F=l<<30|l>>>2,l=a,a=Q;c=c+a&4294967295;e=e+l&4294967295;f=f+F&4294967295;h=h+J&4294967295;m=m+N&4294967295}return[c,e,f,h,m]}function t(a,b){return function(){a.apply(b,arguments)}}
function u(a,b,c,e){a.addEventListener?a.addEventListener(b,c,!!e):a.attachEvent&&a.attachEvent("on"+b,c)}function ja(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function ka(a){return typeof a==="number"}function la(a){return typeof a==="string"}function ma(a){return typeof a==="function"}function na(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function v(){return(new Date).getTime()}
function oa(a){return encodeURIComponent(a)}function s(a,b){if((!!a&&a.constructor===Object)===g)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var e=a.length;c<e;c++)if(b(a[c],c)===j)break}}function pa(a,b){for(var c=0,e=a.length;c<e;c++)if(b(a[c]))return c;return-1}function qa(a){return a===d?0:v()-a}
function ra(a,b){var c,e,f="c"+Math.round(Math.random()*1E9);e=250;a+=(a.indexOf("?")>-1?"&":"?")+(c||"callback")+"=_cb_call."+f;c=document.createElement("script");var h=sa(f,c);c.id=f;c.type="text/javascript";c.charset="UTF-8";c.src=a;var m=document.getElementsByTagName("head");if(m=m&&m[0]){var y=q._cb_call||(q._cb_call={});e=setTimeout(ta(b,h),e);y[f]=ua(b,h,e);m.appendChild(c)}}function ta(a,b){return function(){b();a(d,"TIMEOUT")}}function ua(a,b,c){return function(e){b(c);a(e)}}
function sa(a,b){return function(c){c&&clearTimeout(c);setTimeout(function(){b&&b.parentNode&&b.parentNode.removeChild(b)},0);var e=q._cb_call,f=j;if(e&&(c?delete e[a]:e[a]=va,s(e,function(){f=g;return j}),!f))try{delete q._cb_call}catch(h){q._cb_call=d}}}function va(){}
function wa(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],e=0,f=b.length;e<=f;e++)c[e]=[e];for(var h=0,m=a.length;h<=m;h++)c[0][h]=h;for(var y,l,F,e=1;e<=f;e++)for(h=1;h<=m;h++)y=e-1,l=h-1,F=c[y][l],b.charAt(y)==a.charAt(l)?c[e][h]=F:(l=c[e][l]+1,y=c[y][h]+1,F+=2,c[e][h]=Math.min(l,y,F));return c[b.length][a.length]}function xa(a){return a===d?0:v()-a}function ya(a){return Math.round(a===-1||isNaN(a)?-1:a*1E3)}var za;function Aa(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),s(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function Ba(a,b,c){var e="",f=q.location.href.split("?");f.length&&(f=Aa(f[1]),b=c||b,f[b]&&(e="&"+a+"="+f[b]));return e}function Ca(a,b){return!b?g:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Da(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),e=q.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=e.protocol+a;else if(a.indexOf("/")===0)var f=Ca(e.protocol,e.port)?"":e.port,a=e.protocol+"//"+e.hostname+(f?":"+f:"")+a;else{var f=document.baseURI||e.href,h=f.indexOf("?");h===-1&&(h=f.indexOf("#"));if(h===-1)h=f.length;h=f.lastIndexOf("/",h);a=h===-1?"/"+a:f.substr(0,h)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=e.hostname;if(b.protocol==="")b.protocol=e.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(Ca(b.protocol,b.port)||b.port==="0")b.port="";return b}
function Ea(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function w(a,b,c){a[b]=a[b]||c}function Fa(a,b){for(var c=q[a]||[];c.length;)b(c.shift());q[a]={push:b}}function Ga(a){s(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=Aa(b.src.split("?")[1]),w(a,"uid",b.uid),w(a,"domain",b.domain),j})}function Ha(a,b,c){return a[c]?"&g"+b+"="+encodeURIComponent(a[c]):""}function Ia(a){var b=[];s(a,function(a,e){e.charAt(0)=="_"&&b.push(e+"="+a)});return b.length?"&"+b.join("&"):""};var x={};x.q=function(a){var b=q._sf_async_config;if(!a&&b&&b.noCookies)return i;if(x.q.Ca!==d)return x.q.Ca;var a=v()+"",c,e;try{if((e=q.localStorage).setItem(a,a),c=e.getItem(a)===a,e.removeItem(a),c)return x.q.Ca=e}catch(f){}return x.q.Ca=i};x.e=function(a){var b=x.q();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&v()>c)?(x.remove(a),""):b.getItem(a)||""};
x.create=function(a,b,c){var e=x.q();if(e){var f=new Date;f.setTime(v()+c*1E3);try{e.setItem(a,b),e.setItem(a+"_expires",f.getTime())}catch(h){}}};x.remove=function(a){var b=x.q();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Ja(){var a=document.createElement("script");a.async=g;a.src=(q.location.protocol||"http:")+"//static.chartbeat.com/js/inpage.js";var b=document.getElementsByTagName("head");b&&b.length&&b[0].appendChild(a)}function Ka(a){if(/[\/|\.]chartbeat\.com$/.test(a.origin)){var b=x.q(g),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Ja())}};function La(a,b){var c,b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");var e=[];c=c.getElementsByTagName(b);for(var f=c.length;f--;)c[f].getAttribute(a)&&e.push(c[f]);return e}function Ma(a,b,c){return a===d?j:c===d&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?j:Ma(a.parentNode,b,c)}
function Na(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=La("data-cb-scroll-element"))&&a.length)return a[0][c];if(ka(q[b]))return q[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function Oa(){var a=document,a=a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0;window.innerHeight&&(a=Math.min(window.innerHeight,a));return a}
function Pa(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function Qa(a,b,c){var e=a.ownerDocument.documentElement,f=0,h=typeof c!=="undefined"?c+1:-1;la(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==e&&f!==h;){if(c(a))return a;a=a.parentNode;f++}return i}function Ra(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function Sa(a){a=a||window.event;return!a?i:Qa(a.target||a.srcElement,Ra,10)};var z={},Ta=1;function A(a,b,c){Ta++;z[a]=z[a]||{};z[a][Ta]=[b,c];return Ta}function Ua(a){if(la(a))z[a]=d,delete z[a];else if(ka(a)){var b=g;s(z,function(c){s(c,function(e,f){if(parseInt(f,10)===a)return c[f]=d,delete c[f],b=j});return b})}}function Va(a,b){if(z[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];s(z[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};var B={};
B.A=function(){B.fa?B.sa("pageload"):(B.Lb=[{target:q,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:q,event:"resize"},{target:document.body,event:"mousedown"}],B.ya=i,B.Xa=j,B.ea=i,B.ub={},s(B.Lb,function(a){var b=a.event;u(a.target,b,function(a){B.sa.call(B,b,a)})}),A("f",function(){B.sa("focus")}),B.sa("pageload"),u(document.body,"click",function(a){(a=Sa(a))&&Va("c",a)},g),u(document.body,"contextmenu",function(a){(a=Sa(a))&&Va("r",a)}),
B.fa=g)};B.Qb=function(){var a,b=B.ub.keydown;if(b===d)return j;b=v()-b;return b<=(a||15E3)&&b>=0};B.jb=100;B.sa=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}B.Mc(a);B.ya===i?B.Gb():B.Xa=g};B.Mc=function(a){B.ub[a]=v()};B.Gb=function(){B.ya=q.setTimeout(B.Wb,B.jb);Va("a");B.ea!==i&&q.clearTimeout(B.ea);B.ea=q.setTimeout(function(){Va("i");q.clearTimeout(B.ea);B.ea=i},5E3+B.jb)};
B.Wb=function(){q.clearTimeout(B.ya);B.ya=i;if(B.Xa)B.Xa=j,B.Gb()};var C={};C.Tb=function(){try{C.create("_cb_test","1",1);var a=C.e("_cb_test");C.remove("_cb_test");return a==="1"}catch(b){return j}};C.e=function(a){a+="=";var b="";s(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
C.create=function(a,b,c){var e=q._sf_async_config;if(e&&e.noCookies)return"";e=new Date;e.setTime(v()+c*1E3);a=a+"="+b+("; expires="+e.toGMTString())+"; path=/";return document.cookie=a};C.remove=function(a){return C.e(a)?C.create(a,"",-86400):""};function Wa(a){this.wa=a||"";this.Xb=x.q()!==i||C.Tb();this.Wa=j;Xa(this)}p=Wa.prototype;p.isSupported=n("Xb");
function Xa(a){if(!C.e("_cb_ls")){var b=x.q()!==i,c=C.e("_SUPERFLY_nosample");c&&s(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_nosample",c,600,g)});var e=C.e("_chartbeat3");e&&(a.create("_v__chartbeat3",e,2592E3,g),C.remove("_chartbeat3"));b&&((b=C.e("_chartbeat2"))&&a.create("_chartbeat2",b,94608E3,g),(b=C.e("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,94608E3,g),(b=C.e("_chartbeat5"))&&a.create("_chartbeat5",b,60,g));C.create("_cb_ls","1",2592E3)}}
function Ya(a){var b=a.Wa;a.Wa=j;return b}p.create=function(a,b,c,e){a=e?a:this.wa+a;(x.q()?x:C).create(a,b,c);x.q()&&C.create(a,b,c)};p.update=function(a,b,c,e,f,h,m){a=e?a:this.wa+a;f=la(f)?f:"::";e=(e=this.e(a,g))?e.split(f):[];if(m&&e.length){var y=m(b),l=pa(e,function(a){return m(a)===y});l!==-1&&e.splice(l,1)}ka(h)&&e.length>=h&&e.splice(0,e.length-h+1);e.push(b);this.create(a,e.join(f),c,g)};
p.e=function(a,b){var a=b?a:this.wa+a,c=(x.q()?x:C).e(a);if(!c&&x.q()&&(c=C.e(a))&&C.e("_cb_ls")){this.Wa=g;var e;switch(a){case "_SUPERFLY_nosample":e=600;break;case "_chartbeat4":e=3600;break;case "_cb_cp":e=3600;break;case "_chartbeat3":e=2592E3;break;default:e=94608E3}x.create(a,c,e)}return c};p.remove=function(a,b){a=b?a:this.wa+a;(x.q()?x:C).remove(a);x.q()&&C.remove(a)};var D=function(){var a,b;s(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof q.document[a]==="boolean")return b=c,j});var c={};if(b!==d)c.sb=a,c.fb=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),c.za=b+"visibilitychange";return c}();
D.A=function(){if(!D.fa)D.oa=D.zb(),D.za&&q.document.addEventListener&&q.document.addEventListener(D.za,D.Gc,j),D.pb("focus","onfocusin",D.Ka),D.pb("blur","onfocusout",D.wb),D.oa&&D.Ka(),D.fa=g};D.Rc=function(){return D.oa};D.Ka=function(){D.oa=g;Va("f")};D.wb=function(){D.oa=j;Va("b")};D.pb=function(a,b,c){q.addEventListener?q.addEventListener(a,c,j):q.document.attachEvent&&q.document.attachEvent(b,c)};
D.zb=function(){var a=g;q.document.hasFocus&&(a=q.document.hasFocus());var b=j;D.sb&&(b=q.document[D.sb]);return a&&!b};D.Gc=function(){D.zb()?D.Ka():D.wb()};function Za(a){var b=i;if(a&&(b=$a()))return b;var c=q.location,b=ab(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),e=/&utm_[^=]+=[^&]+/ig;(c=e.exec(c.search))&&(a=a.replace(e,""));e=/\?utm_[^=]+=[^&]+(.*)/i;(c=e.exec(a))&&(a=a.replace(e,c[1]!=""?"?"+c[1]:""));return b+a}function $a(){var a=i;s(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=Da(b.href),a=ab(b.pathname)+b.search+b.hash,j});return a}
for(var bb={},cb=0;cb<81;cb++)bb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(cb)]=g;function db(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return bb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function ab(a){if(!la(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,db);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};var E={Nb:{IDLE:0,Pc:1,Oc:2,Mb:3},H:0};E.A=function(){if(!E.fa)A("a",E.ac,E),A("i",E.dc,E),A("f",E.cc,E),A("b",E.bc,E),E.fa=g};E.h=function(){return E.H};E.ac=function(){E.H===1?E.U(3):E.H===0&&E.U(2)};E.dc=function(){E.H===3?E.U(1):E.H===2&&E.U(0)};E.cc=function(){(E.H===0||E.H===2)&&E.U(3)};E.bc=function(){E.H===3?E.U(2):E.H===1&&E.U(0)};E.U=function(a){E.H=a;Va("s",a)};function eb(a,b){this.Ga=a||d;this.La=b||d;this.Z=this.ab=0}p=eb.prototype;p.A=function(){this.Z=this.ab=0;this.ja=i;this.Jc=A("s",this.rb,this);this.rb(E.h())};p.total=function(){this.ab+=this.Z;this.Z=0;return this.ab};p.rb=function(a){q.clearInterval(this.ja);this.ja=i;if(a===E.Nb.Mb)this.ja=q.setInterval(t(this.hc,this),1E3)};p.hc=function(){if(this.Ga===d||this.Ga())this.Z++,this.La&&this.La()};p.terminate=function(){q.clearInterval(this.ja);this.ja=i;Ua(this.Jc)};
p.ca=function(){this.terminate();this.La=this.Ga=d};function ea(){this.b=q._sf_async_config||{};this.Fa=t(this.xc,this);this.Y=[];this.g=new Wa(this.Kc);this.T=j;this.O=new eb;this.Na=t(this.ua,this);u(q,"unload",this.Na);fb(this)||this.A()}p=ea.prototype;p.Ta=g;function fb(a){if(D.fb&&document[D.fb]==="prerender"){a.T=g;var b=t(function(){if(this.T&&document[D.fb]!=="prerender")this.T=j,this.A(),gb(this),window.setTimeout(function(){document.removeEventListener(D.za,b,j)},100)},a);document.addEventListener(D.za,b,j);return g}return j}
p.A=function(){this.pa=this.$=0;this.ia=v();this.aa=ha(hb(this));this.Sa=g;this.qa=72E5;this.Ab=0;if(this.Ta){var a=+this.b.sessionLength;if(!isNaN(a))this.qa=a*6E4}this.O.A();E.A();B.A();D.A();this.ha=0;this.Pb=A("a",this.jc,this)};function gb(a){if(!a.g.e("_SUPERFLY_nosample")&&!a.T)a.ic?a.Va():(a.ic=g,!q._sf_async_config&&!q._cbq?(a.ta=t(a.Va,a),u(q,"load",a.ta)):a.Va())}
p.Va=function(){var a=q._sf_startpt,b=q._sf_endpt;if(ka(a))this.va=ka(b)?b-a:v()-a;B.A();this.ga=setInterval(t(this.K,this),15E3);this.K()};p.K=function(){var a=this.O.Z,a=this.b.reading&&+this.b.reading||a>0;if(this.pa<this.$&&!a)this.pa++;else{var b;if(za===d)b=q.navigator.userAgent,za=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=za;b&&!a?this.pa++:(a?this.$=0:this.Ba(),this.pa=0,this.Y.push(0),this.Y.length>18&&this.Y.shift(),this.Ta&&v()-this.ia>=this.qa?this.terminate():this.Pa())}};
p.xc=function(){this.Y.push(1);var a=0;s(this.Y,function(b){a+=b});a<3?(this.Sa=g,this.Ba()):(this.terminate(),this.g.create("_SUPERFLY_nosample","1",600))};p.ua=k();p.jc=function(){var a=ib(this);this.ha=Math.max(this.ha,a)};function ib(a){return Na(!!a.b.scrollElement)}p.Ba=function(){var a=this.$;this.$=a=a?Math.min(a*2,16):1};p.Nc=function(a,b){if(!this.T)this.ua(),this.terminate(),this.eb=q.location.protocol+"//"+this.b.domain+this.b.path,this.b.path=ab(a),b&&(this.b.title=b),this.A(),gb(this)};
function jb(a){if(a.eb)return g;a=(document.referrer||"").indexOf("://"+q.location.host+"/");return a!=-1&&a<9}function kb(a){a=a.eb;if(!a&&(a=document.referrer||"")){var b=Da(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=ab(b.pathname),a=Ea(b)}return encodeURIComponent(a)}function lb(a){a=a.b.title.slice(0,100);return encodeURIComponent(a)}
function hb(a){var b=q.navigator,c=q.window.screen,e=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];s(b.plugins,function(a){e.push(a.name+a.description+a.filename+a[0].type)});b=q.performance;e=e.concat([b&&b.now?b.now():"",kb(a),document.title,q.location.href,v(),Pa("Width"),Pa("Height"),ga()]);return e.join()}function mb(a){var b="",c=a.g.e("_chartbeat4");c&&(s(c.split("::"),function(a){b+="&z="+encodeURIComponent(a)}),a.g.remove("_chartbeat4"));return b}
p.terminate=function(){this.O.terminate();Ua(this.Pb);this.ta!==d&&ja(q,"load",this.ta);clearInterval(this.ga)};p.ca=function(){this.terminate();ja(q,"unload",this.Na);this.Na=this.ta=this.g=this.Y=this.Fa=this.b=i;this.O.ca();this.O=i};function nb(a){for(var b=a.offsetLeft,c=a.offsetTop,e=j,f=a.offsetParent;a&&a!==d&&a!==document.body;){if(a===f)b+=a.offsetLeft,c+=a.offsetTop,f=a.offsetParent;var h=a,m=d;m=q.getComputedStyle?(h=q.getComputedStyle(h,i))&&(h.position||h.getPropertyValue("position")):h.currentStyle?h.currentStyle.position:h.style&&h.style.position;if((m||"")==="fixed"){e=g;break}a=a.parentElement}e&&(b+=0,c+=0);return{x:b,y:c}};function ob(a,b){for(var c=b||document.documentElement,e=[],f=i,h=a,m,y,l,F,J,N;h&&h!==c;){m=h.nodeName.toLowerCase();f=h;y=f.nodeName;if((h=h.parentNode)&&h!==document.documentElement){l=h.children;F=0;for(J=0,N=l.length;J<N;J++){if(f===l[J]){m+="["+(1+J-F)+"]";break}l[J].nodeName!==y&&F++}}e.unshift(m)}return e.join("/")};function G(){ea.call(this);Fa("_cbq",t(this.Db,this));"postMessage"in window&&u(q,"message",t(this.ec,this))}da(G);p=G.prototype;
p.A=function(){G.W.A.call(this);this.Aa=i;Ga(this.b);var a=q.location;w(this.b,"pingServer","ping.chartbeat.net");w(this.b,"title",document.title);w(this.b,"domain",a.host);this.b.path=this.b.path?ab(this.b.path):Za(!!this.b.useCanonical);this.S=a.host.replace(/^www\./,"");this.b.domain=this.b.domain.replace(/^www\./,"");a=(this.g.e("_chartbeat2",g)||"").split(".");a.length>4&&(a=[]);var b=v(),c,e="1",f=a&&+a[2];c=a&&a[3];if(a&&f&&c)if(e=Math.abs((na(b)-na(f))/864E5)){e=Math.min(e,16)-1;for(f="";e--;)f+=
0;e=(c+f+"1").slice(-16)}else e=c;c=e;var e=(this.g.e("_chartbeat2",g)||"").split("."),h=v(),f=h-+(e[1]||0);h-=+(e[2]||0);this.Ia=e[0]&&f>18E5&&h<2592E6?0:1;a[0]||(a[0]=this.b.utoken||ha(hb(this),3),a[1]=b);a[2]=b;a[3]=c;this.bb=a[0];this.P=a.join(".");this.g.create("_chartbeat2",this.P,94608E3,g);this.b.utoken=this.bb;var m;b=+a[1];c=+a[2];if((a=a[3])&&b&&c)m=(Math.min((Math.abs((na(c)-na(b))/864E5)||0)+1,16,a.length)-1).toString(16),m+=("0000"+parseInt(a,2).toString(16)).slice(-4);this.qb=m;this.Rb=
A("c",this.oc,this);this.Sb=A("r",this.pc,this)};p.Ob=function(a){this.Aa=a};p.ua=function(){this.g.update("_chartbeat4",["t="+this.aa,"E="+this.O.total(),"x="+ib(this),"c="+Math.round((v()-this.ia)/600)/100,"y="+Pa("Height"),"w="+Oa()].join("&"),3600,d,d,1)};
p.Pa=function(a){this.Ab++;var b=this.b,c=ib(this);this.ha=Math.max(this.ha,c);var e=Math.round((v()-this.ia)/600)/100,f=0,h=0,m=0,y=this.O.Z;B.Qb()?h=1:this.b.reading&&+this.b.reading||y>0||e<0.09?f=1:m=1;var l="",F="",J="",N="",Q="",P=jb(this);if(this.Sa){this.Sa=j;var l=(P?"&v=":"&r=")+kb(this),F="&i="+lb(this),S=this.b.hudTrackable;S!==d&&(J="&L="+(S?"1":"0"));if(P&&(P=pb(this)))l="&v="+encodeURIComponent(P.path),N="&K="+qb(P),P.Ja>1&&(N+="&l1="+P.Ja);b.alias&&(Q="&PA="+encodeURIComponent(b.alias));
this.eb&&(l+="&vp=1")}a=a?"&KK="+qb(a,g):"";P=this.va?"&b="+this.va:"";S=this.Aa?"&A="+this.Aa:"";b=(q.location.protocol||"http:")+"//"+b.pingServer+"/ping?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&u="+this.bb+"&d="+encodeURIComponent(this.S)+"&g="+b.uid+Ha(b,0,"sections")+Ha(b,1,"authors")+Ha(b,3,"sponsorName")+Ha(b,4,"type")+(!b.noCookies&&this.g.isSupported()?"&n="+this.Ia:"&nc=1")+(this.qb?"&f="+this.qb:"")+"&c="+e+"&x="+c+"&m="+this.ha+"&y="+Pa("Height")+"&o="+Pa("Width")+
"&w="+Oa()+"&j="+Math.round((this.$+2)*15E3/1E3)+"&R="+f+"&W="+h+"&I="+m+"&E="+this.O.total()+"&e="+y+l+N+a+Q+P+S+Ba("C","utm_campaign",b.campaignTag)+Ba("M","utm_medium",b.mediumTag)+"&t="+this.aa+"&V=45"+mb(this)+F+J+"&tz="+(new Date).getTimezoneOffset()+(Ya(this.g)?"&l=1":"")+Ia(b)+"&sn="+this.Ab+"&_";this.T||fa(b,this.Fa)};
p.ec=function(a){var b=this.b;if(a.origin==="http://"+(b.playerdomain||this.S)){var c=a.data;la(c)&&c.indexOf("cbqpush::")===0?(a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Db(a))):c=="cbdata?"&&(b="domain="+encodeURIComponent(b.domain)+"&path="+encodeURIComponent(b.path)+"&title="+lb(this)+"&referrer="+kb(this)+"&internal="+(jb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.S)+"&utoken="+this.bb,a.source.postMessage(b,"*"))}};
p.Db=function(a){this.b[a[0]]=a[1];this.$=0};function rb(a){a=a.replace(/-{2,}/g,"-");a=Da(a);a.pathname=ab(a.pathname);return a}p.oc=function(a){sb(this,a,"c")};p.pc=function(a){sb(this,a,"r")};
function sb(a,b,c){if(a.Ta&&v()-a.ia>=a.qa)a.terminate();else{var e=b.href||"",e=rb(e);if(!(e.hostname!==q.location.hostname||e.protocol.indexOf("http")!==0)){var e=Ea(e),f=Qa(b,function(a){return a.id}),h=ob(b,f);f&&(h&&(h="/"+h),h="*[@id='"+f.id+"']"+h);f=ha(h);b=nb(b);c={left:b.x,top:b.y,path:a.b.path,href:e,ib:f,hb:h,Ua:c,Ja:0};a.Pa(c);a.g.update("_chartbeat5",tb(c),60,j,d,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function qb(a,b){var c=[a.left,a.top,a.ib,encodeURIComponent(a.hb),a.Ua];b&&c.push(encodeURIComponent(a.href));return c.join("::")}function tb(a){var b=encodeURIComponent(a.hb),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.ib,b,a.Ua].join(",")}
function pb(a){var b=a.g.e("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,e,f;if(b===1)e=c[0].split(","),f=0;else{var h,m=rb(q.location.href),y=Ea(m);s(c,function(a,b){var c=a.split(","),m=wa(y,decodeURIComponent(c[3]));if(m===0)return e=c,f=b,j;if(h===d||m<h)h=m,e=c,f=b})}c.splice(f,1);a.g.create("_chartbeat5",c.join("::"),60);(a=e[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:e[0],top:e[1],path:decodeURIComponent(e[2]),ib:e[4]||"",hb:a,Ua:e.length>6?e[6]:"c",
Ja:b}}p.terminate=function(){Ua(this.Rb);Ua(this.Sb);G.W.terminate.call(this)};var H="ct",I="s1";function L(a){this.a=a;this.d=this.f=j;this.c=v();this.J=this.M=d;this.D()}p=L.prototype;p.D=function(){this.a.currentTime()>0&&!this.a.paused&&!this.a.ended&&this.C();this.a.on("play",t(this.C,this));this.a.ready(t(this.G,this))};p.G=function(){this.f=g};p.C=function(){this.d=g};p.j=n("f");p.v=function(){var a="";return a=(a=this.a.options()["data-media"])&&a.hasOwnProperty("title")?a.title:this.a.el().attributes.title&&this.a.el().attributes.title.value};p.i=function(){return this.a.src()||""};
p.o=function(){return H};p.k=o("");p.w=function(){var a=this.a.duration();return ya(a)};p.h=function(){return!this.d?I:this.a.ended()?"s4":this.a.paused()?"s3":"s2"};p.p=function(){var a=this.a.currentTime();return ya(a)};p.n=o(-1);p.u=function(){return this.a.poster()||""};p.r=k();p.m=k();p.z=function(){return xa(this.c)};p.s=n("M");p.l=n("J");p.t=o("BCN");L.prototype.getStrategyName=L.prototype.t;L.prototype.isReady=L.prototype.j;L.prototype.getTitle=L.prototype.v;L.prototype.getVideoPath=L.prototype.i;
L.prototype.getContentType=L.prototype.o;L.prototype.getAdPosition=L.prototype.k;L.prototype.getTotalDuration=L.prototype.w;L.prototype.getState=L.prototype.h;L.prototype.getCurrentPlayTime=L.prototype.p;L.prototype.getBitrate=L.prototype.n;L.prototype.getThumbnailPath=L.prototype.u;L.prototype.getPlayerType=L.prototype.r;L.prototype.getAutoplayType=L.prototype.m;L.prototype.getViewStartTime=L.prototype.z;L.prototype.getSections=L.prototype.s;L.prototype.getAuthors=L.prototype.l;
L.verify=function(a){return a.controlBar!==d};function M(a){this.Jb=this.S=d;this.f=j;this.Cb=this.lb=-1;this.N=i;this.a=a;this.d=j;this.Oa=g;this.c=v();this.Qa="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var e=a[c];if((e.indexOf("chartbeat")>=0||e.indexOf("localhost")>=0)&&e.indexOf(".js")>=0){this.Qa=e;break}}if(this.Qa)a=Aa(this.Qa),this.S=a.domain,this.Jb=a.uid;a=window.brightcove;this.a=a.api.getExperience();b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);b.getReady()?
this.yb():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,r(this.yb,this))}p=M.prototype;
p.yb=function(){var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.lb=Math.round(a)});b.getCurrentVideo(function(a){c.N=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,r(this.zc,this));b.addEventListener(a.STOP,r(this.Ac,this));b.addEventListener(a.COMPLETE,r(this.qc,this));b.addEventListener(a.BEGIN,r(this.C,this));this.f=g};p.zc=function(a){this.Cb=a.position;this.Q=this.Oa=j};p.Ac=function(){this.Oa=g};
p.qc=function(){this.Q=g};p.C=function(){this.Q=j;if(!this.d)this.d=g};p.j=n("f");p.v=function(){var a="";this.N&&(a=this.N.displayName);return a};p.i=function(){var a="";this.N&&(a="video@"+this.S+"/"+this.N.id);return a};p.o=function(){return H};p.k=o("");p.w=n("lb");p.h=function(){return!this.d?I:this.Q?"s4":this.Oa?"s3":"s2"};p.p=n("Cb");p.n=o(-1);p.u=function(){var a="";this.N&&(a=this.N.thumbnailURL);return a};p.r=k();p.z=function(){return isNaN(this.c)?0:qa(this.c)};p.l=k();
p.s=function(){var a;this.N&&(a=this.N.tags);return a};p.m=o("unkn");p.t=o("BC");p.Zb=n("S");p.$b=n("Jb");M.prototype.isReady=M.prototype.j;M.prototype.getTitle=M.prototype.v;M.prototype.getVideoPath=M.prototype.i;M.prototype.getContentType=M.prototype.o;M.prototype.getAdPosition=M.prototype.k;M.prototype.getTotalDuration=M.prototype.w;M.prototype.getState=M.prototype.h;M.prototype.getCurrentPlayTime=M.prototype.p;M.prototype.getBitrate=M.prototype.n;M.prototype.getThumbnailPath=M.prototype.u;
M.prototype.getPlayerType=M.prototype.r;M.prototype.getViewStartTime=M.prototype.z;M.prototype.getAuthors=M.prototype.l;M.prototype.getSections=M.prototype.s;M.prototype.getAutoplayType=M.prototype.m;M.verify=function(a){return a===window.brightcove};M.prototype.getStrategyName=M.prototype.t;M.prototype.getHost=M.prototype.Zb;M.prototype.getUid=M.prototype.$b;function R(){this.a=window.flowplayer();this.d=this.f=j;this.c=v();this.J=this.M=d;this.Ib=this.Ya="";this.Ha=d;this.D()}var ub=/url\(['"]?([^'"\)]*)['"]?\)/;p=R.prototype;
p.ob=function(){var a=this.i(),b=La("name","param"),c=d;s(b,function(b){if(b.attributes.name.value==="flashvars"&&b.value.indexOf(a)!==-1)return c=b,j});if(c===d)return j;b=Ma(c,"data-swf");if(b===j)return j;var e=b.style.background;if(e){if(e=e.match(ub))this.Ya=e[1]}else this.Ya=b.attributes.poster&&b.attributes.poster.value;this.Ib=b.title;this.Ha!==d&&clearInterval(this.Ha);return g};
p.D=function(){this.a.Tc?this.G():this.a.bind("ready",r(this.G,this));this.a.bind("resume",r(this.C,this));this.a.Sc&&this.C()};p.G=function(){if(this.ob()===j)this.Ha=setInterval(r(this.ob,this),1E3);this.f=g};p.C=function(){if(!this.d)this.d=g};p.j=n("f");p.v=n("Ib");p.i=function(){return this.a.video.url};p.o=function(){return H};p.k=o("");p.w=function(){return this.a.video.duration};p.h=function(){return!this.d?I:this.a.Qc?"s4":this.a.paused?"s3":"s2"};p.p=function(){return this.a.video.time};
p.n=o(-1);p.u=n("Ya");p.r=k();p.m=k();p.z=function(){return isNaN(this.c)?0:qa(this.c)};p.s=n("M");p.l=n("J");p.t=o("FP");R.prototype.getStrategyName=R.prototype.t;R.prototype.isReady=R.prototype.j;R.prototype.getTitle=R.prototype.v;R.prototype.getVideoPath=R.prototype.i;R.prototype.getContentType=R.prototype.o;R.prototype.getAdPosition=R.prototype.k;R.prototype.getTotalDuration=R.prototype.w;R.prototype.getState=R.prototype.h;R.prototype.getCurrentPlayTime=R.prototype.p;R.prototype.getBitrate=R.prototype.n;
R.prototype.getThumbnailPath=R.prototype.u;R.prototype.getPlayerType=R.prototype.r;R.prototype.getAutoplayType=R.prototype.m;R.prototype.getViewStartTime=R.prototype.z;R.prototype.getSections=R.prototype.s;R.prototype.getAuthors=R.prototype.l;R.verify=function(){return!!window.flowplayer};function T(a){this.a=a;this.d=this.f=j;this.c=v();this.J=this.M=d;this.D()}p=T.prototype;p.D=function(){this.a.readyState>2&&this.G();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.C();this.a.addEventListener("canplay",t(this.G,this));this.a.addEventListener("playing",t(this.C,this))};p.G=function(){this.f=g};p.C=function(){this.d=g};p.j=n("f");p.v=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};p.i=function(){return this.a.currentSrc||""};p.o=function(){return H};
p.k=o("");p.w=function(){return ya(this.a.duration)};p.h=function(){return!this.d?I:this.a.ended?"s4":this.a.paused?"s3":"s2"};p.p=function(){return ya(this.a.currentTime)};p.n=o(-1);p.u=function(){return this.a.poster||""};p.r=k();p.m=k();p.z=function(){return xa(this.c)};p.s=n("M");p.l=n("J");p.t=o("H5");T.prototype.getStrategyName=T.prototype.t;T.prototype.isReady=T.prototype.j;T.prototype.getTitle=T.prototype.v;T.prototype.getVideoPath=T.prototype.i;T.prototype.getContentType=T.prototype.o;
T.prototype.getAdPosition=T.prototype.k;T.prototype.getTotalDuration=T.prototype.w;T.prototype.getState=T.prototype.h;T.prototype.getCurrentPlayTime=T.prototype.p;T.prototype.getBitrate=T.prototype.n;T.prototype.getThumbnailPath=T.prototype.u;T.prototype.getPlayerType=T.prototype.r;T.prototype.getAutoplayType=T.prototype.m;T.prototype.getViewStartTime=T.prototype.z;T.prototype.getSections=T.prototype.s;T.prototype.getAuthors=T.prototype.l;
T.verify=function(a){var b=a instanceof HTMLElement&&a.nodeName==="VIDEO",a=a.getAttribute&&a.getAttribute("data-account")!==i;return b&&!a};function U(a){this.a=a();this.d=this.Q=this.f=j;this.c=v();this.D()}p=U.prototype;p.D=function(){this.a.onReady(r(this.G,this));this.a.onTime(r(this.Cc,this));this.a.onComplete(r(this.Dc,this))};p.G=function(){this.f=g};p.Cc=function(){this.a.getDuration();this.Q=j;if(!this.d)this.d=g};p.Dc=function(){this.Q=g};p.j=function(){return this.f||this.a.getState()!==d};p.v=function(){var a=vb(this);return!a?"":a.title};
function vb(a){if(a.a.getPlaylistIndex===d)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return i;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?i:b[a]}p.i=function(){var a=vb(this);return!a?"":a.file};p.o=function(){return H};p.k=o("");p.w=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};p.h=function(){if(!this.d)return I;var a=this.a.getState();return this.Q?"s4":a==="PAUSED"?"s3":"s2"};p.p=function(){return this.a.getPosition()};p.n=o(-1);
p.u=function(){var a=vb(this);return!a?"":a.image};p.r=k();p.z=function(){return isNaN(this.c)?0:qa(this.c)};p.l=k();p.s=k();p.m=o("unkn");p.t=o("JW");U.prototype.getStrategyName=U.prototype.t;U.prototype.isReady=U.prototype.j;U.prototype.getTitle=U.prototype.v;U.prototype.getVideoPath=U.prototype.i;U.prototype.getContentType=U.prototype.o;U.prototype.getAdPosition=U.prototype.k;U.prototype.getTotalDuration=U.prototype.w;U.prototype.getState=U.prototype.h;U.prototype.getCurrentPlayTime=U.prototype.p;
U.prototype.getBitrate=U.prototype.n;U.prototype.getThumbnailPath=U.prototype.u;U.prototype.getPlayerType=U.prototype.r;U.prototype.getViewStartTime=U.prototype.z;U.prototype.getAuthors=U.prototype.l;U.prototype.getSections=U.prototype.s;U.prototype.getAutoplayType=U.prototype.m;U.verify=function(a){return a===window.jwplayer};function V(a){this.a=a;this.Kb="";this.F=I;this.R=H;this.I="";this.c=v();this.D()}p=V.prototype;p.D=function(){this.a.kBind("playerStateChange.cb",r(this.Fc,this));this.a.kBind("playerUpdatePlayhead.cb",r(this.yc,this));this.a.kBind("playerPlayEnd.cb",r(this.Ec,this));this.a.kBind("adStart.cb",r(this.lc,this));this.a.kBind("adEnd.cb",r(this.kc,this));this.a.kBind("switchingChangeComplete.cb",r(this.Bc,this))};
p.Fc=function(a){switch(a){case "playing":this.F="s2";break;case "buffering":this.F="s3";break;case "paused":this.F="s3"}};p.yc=function(){this.F="s2";this.a.kUnbind("playerUpdatePlayhead.cb")};p.Ec=function(){this.F="s4"};p.lc=function(a){this.R="ad";switch(a){case "pre":this.I="a1";break;case "post":this.I="a3";break;case "mid":this.I="a2";break;case "main":this.I="a5"}};p.kc=function(){this.R=H};p.Bc=function(a,b){this.Ub=b};p.j=function(){return this.a.evaluate("{mediaProxy.entry.name}")!=i};
p.v=function(){return this.a.evaluate("{mediaProxy.entry.name}")};p.i=function(){if(!this.j())return this.Kb;var a=this.a.evaluate("{mediaProxy.entry.id}");return(this.Kb=a)||""};p.o=n("R");p.k=n("I");p.w=function(){var a=this.a.evaluate("{duration}");return ya(a)};p.h=n("F");p.p=function(){var a=this.a.evaluate("{video.player.currentTime}");return ya(a)};p.n=n("Ub");p.u=function(){return this.a.evaluate("{mediaProxy.entry.thumbnailUrl}")||""};p.r=k();
p.m=function(){var a=this.a.evaluate("{configProxy.flashvars.autoPlay}"),b=this.a.evaluate("{configProxy.flashvars.playlistAPI.autoContinue}"),c=this.a.evaluate("{playlistAPI.dataProvider.selectedIndex}");return b&&c>0?"cont":a?"auto":"man"};p.z=function(){return isNaN(this.c)?0:xa(this.c)};p.s=function(){var a=this.a.evaluate("{mediaProxy.entry.tags}");if(a)return a.split(",")};p.l=function(){var a=this.a.evaluate("{mediaProxy.entry.creatorId}");if(a)return[encodeURIComponent(a)]};p.t=o("KT");
V.prototype.getStrategyName=V.prototype.t;V.prototype.isReady=V.prototype.j;V.prototype.getTitle=V.prototype.v;V.prototype.getVideoPath=V.prototype.i;V.prototype.getContentType=V.prototype.o;V.prototype.getAdPosition=V.prototype.k;V.prototype.getTotalDuration=V.prototype.w;V.prototype.getState=V.prototype.h;V.prototype.getCurrentPlayTime=V.prototype.p;V.prototype.getBitrate=V.prototype.n;V.prototype.getThumbnailPath=V.prototype.u;V.prototype.getPlayerType=V.prototype.r;
V.prototype.getAutoplayType=V.prototype.m;V.prototype.getViewStartTime=V.prototype.z;V.prototype.getSections=V.prototype.s;V.prototype.getAuthors=V.prototype.l;V.verify=function(a){return typeof a.kBind=="function"};function W(a){this.kb=d;this.a=a;this.vb=d;this.f=j;this.X=d;this.d=j;this.J=this.M=this.c=d;this.kb=q.OO;this.vb=this.a.mb;this.c=v();this.D()}p=W.prototype;
p.D=function(){var a=this.vb,b=this.kb.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",r(this.G,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",r(this.nc,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",r(this.C,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",r(this.mc,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",r(this.wc,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",r(this.rc,this))};p.G=function(){this.f=g};
p.nc=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.X=a===0?"a1":wb(a,b)?"a3":"a2"};p.C=function(){this.d=g};p.mc=function(){this.X=d};p.wc=k();p.j=function(){var a=this.a.getState();if(a==="ready"||a==="playing"||a==="paused")this.f=g;return this.f};p.v=function(){var a=this.a.getItem();return a?a.title:""};p.i=function(){return(this.a.getItem()||{}).embedCode||this.a.embedCode||""};p.o=function(){return this.X===d?H:"ad"};
p.k=function(){return this.X?this.X:""};p.w=function(){var a=this.a.getDuration();return a===-1||isNaN(a)?-1:a*1E3};p.h=function(){if(!this.d)return I;if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return wb(a,b)?"s4":"s2"};function wb(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}p.rc=function(){this.X=d};
p.p=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};p.n=function(){return this.a.getTargetBitrate()};p.u=function(){var a=this.a.getItem();return!a?"":a.promo||a.promo_image||a.thumbnail_image};p.r=k();p.m=k();p.z=function(){return isNaN(this.c)?0:xa(this.c||0)};p.s=n("M");p.l=n("J");p.t=o("OO");W.prototype.getStrategyName=W.prototype.t;W.prototype.isReady=W.prototype.j;W.prototype.getTitle=W.prototype.v;W.prototype.getVideoPath=W.prototype.i;
W.prototype.getContentType=W.prototype.o;W.prototype.getAdPosition=W.prototype.k;W.prototype.getTotalDuration=W.prototype.w;W.prototype.getState=W.prototype.h;W.prototype.getCurrentPlayTime=W.prototype.p;W.prototype.getBitrate=W.prototype.n;W.prototype.getThumbnailPath=W.prototype.u;W.prototype.getPlayerType=W.prototype.r;W.prototype.getAutoplayType=W.prototype.m;W.prototype.getViewStartTime=W.prototype.z;W.prototype.getSections=W.prototype.s;W.prototype.getAuthors=W.prototype.l;
W.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("adPlaying")};function X(a){this.a=a;this.L=i;this.F=I;this.R=H;this.I="";this.c=v();this.a.controller.plugInLoaded&&this.a.controller.plugInLoaded(this)}p=X.prototype;p.tb=function(a){this.D(a.controller)};
p.D=function(a){a.addEventListener("OnLoadRelease",t(this.xb,this));a.addEventListener("OnLoadReleaseUrl",t(this.xb,this));a.addEventListener("OnMediaPlay",t(this.tc,this));a.addEventListener("OnMediaStart",t(this.vc,this));a.addEventListener("OnMediaPause",t(this.Ma,this));a.addEventListener("OnMediaComplete",t(this.sc,this));a.addEventListener("OnMediaError",t(this.Ma,this));a.addEventListener("OnMediaBuffer",t(this.Ma,this));a.addEventListener("OnMediaPlaying",t(this.uc,this))};
p.xb=function(a){if(a.data&&a.data.pid&&a.data.title)this.L=a.data};p.tc=function(){this.F="s2"};p.vc=function(a){this.F="s2";a=a.data.baseClip;a.isAd?(this.R="ad",this.I=a.isMid?"a2":"a1"):(this.R=H,this.I="")};p.Ma=function(){if(this.F!=I)this.F="s3"};p.sc=function(){this.F="s4"};p.uc=function(a){this.Yb=a.currentTime};p.j=function(){return this.L!=i};p.v=function(){return this.L.title};p.i=function(){return!this.L?"":this.L.pid};p.o=n("R");p.k=n("I");p.w=function(){return this.L.duration};
p.h=n("F");p.p=n("Yb");p.n=function(){return this.L.bitrate};p.u=function(){return this.L.defaultThumbnailUrl};p.r=k();p.m=k();p.z=function(){return isNaN(this.c)?0:this.c===d?0:v()-this.c};p.s=function(){var a=[];s(this.L.categories,function(b){a.push(encodeURIComponent(b.name))});return a};p.l=k();p.t=o("TP");X.prototype.tb.initialize=X.prototype.tb;X.prototype.getStrategyName=X.prototype.t;X.prototype.isReady=X.prototype.j;X.prototype.getTitle=X.prototype.v;X.prototype.getVideoPath=X.prototype.i;
X.prototype.getContentType=X.prototype.o;X.prototype.getAdPosition=X.prototype.k;X.prototype.getTotalDuration=X.prototype.w;X.prototype.getState=X.prototype.h;X.prototype.getCurrentPlayTime=X.prototype.p;X.prototype.getBitrate=X.prototype.n;X.prototype.getThumbnailPath=X.prototype.u;X.prototype.getPlayerType=X.prototype.r;X.prototype.getAutoplayType=X.prototype.m;X.prototype.getViewStartTime=X.prototype.z;X.prototype.getSections=X.prototype.s;X.prototype.getAuthors=X.prototype.l;
X.verify=function(a){return typeof a.controller!=="undefined"};function Y(a,b){this.a=a;this.Hb=b;this.da=window.location!=window.parent.location;this.Bb=j;this.Lc=v();this.Kc="_v_";ea.call(this)}da(Y);var xb=q.QUICK_TEST?1E4:6E4,yb="autoDetect",zb={};p=Y.prototype;
p.A=function(){this.Ia=(this.P=this.g.e("_chartbeat3"))?0:1;this.gb=this.Fb=g;this.Ea=j;this.xa=this.Ra=this.nb=this.V=d;this.ba=15E3;this.la=d;this.Hc=this.Za=this.$a=this.ma=this.na=0;var a=q.location;this.Eb=j;if(!this.P||this.P.length===0)this.P=ha(hb(this),3);this.g.create("_chartbeat3",this.P,2592E3);var b;(b=this.Hb)&&ma(b)?(this.B=new b(this.a),b=g):b=j;if(b){w(this.b,"pingServer","ping.chartbeat.net");w(this.b,"title",document.title);w(this.b,"domain",a.host);w(this.b,"path",Za(!!this.b.useCanonical));
this.B.getPlayerType&&w(this.b,"video_type",this.B.getPlayerType());this.nb=setInterval(t(this.Vb,this),1E3);if(this.da===g)this.ra=t(this.fc,this),u(window,"message",this.ra),this.la=setInterval(this.Ic,1E3);Y.W.A.call(this)}};p.Ba=k();
p.K=function(){if(this.B){if(!this.B.getVideoPath())this.gb=g;if(!this.gb)return v()-this.ia>=this.qa&&clearInterval(this.V),Y.W.K.call(this);if(this.B.isReady())this.Ea=this.gb=j,this.Ra=Ab(this),Bb(this),this.V=setInterval(t(this.Da,this),100),Y.W.K.call(this);else if(!this.Ea){this.Ea=g;if(this.Hc++>150)throw"Error: Video strategy never reported its ready state";clearInterval(this.ga);this.ga=setInterval(t(this.K,this),100)}}};
p.Pa=function(){if(this.B){var a=this.b,b=this.B,c=b.getState(),e=b.getVideoPath(),f=this.da?[]:q._cbq||(q._cbq=[]),h=b.getViewStartTime(),m=b.getThumbnailPath(),y=b.getAutoplayType?b.getAutoplayType():d,h=h===-1?-1:h/1E3,m=m?encodeURIComponent(m):d;if(!zb.path||zb.path===e||c==="s2"&&zb.state!=="s2")switch(zb={path:e,state:c},f.push(["_vi",oa(b.getTitle())]),f.push(["_vp",e]),f.push(["_vdd",encodeURIComponent("video@"+(a.videodomain||a.domain))]),f.push(["_vs",b.getState()]),b.getContentType&&f.push(["_vt",
b.getContentType()]),b.getAdPosition&&f.push(["_vap",b.getAdPosition()]),f.push(["_vtn",oa(b.getThumbnailPath())]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case I:case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}a=Cb(this)+Z("_vt",b.getContentType?b.getContentType():"")+Z("_vap",b.getAdPosition?b.getAdPosition():"")+Z("_vs",c)+Z("_vbr",b.getBitrate?b.getBitrate():"")+Z("_vvs",h)+Z("_vpt",b.getCurrentPlayTime())+Z("_vtn",m)+Z("_vaup",y||"unkn")+Z("_vplt",a.video_type)+
Z("_vce",this.Za)+Z("c",Math.round(qa(this.Lc)/600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.$a+"&j="+(this.ba/1E3+15)+Db(this)+"&tz="+(new Date).getTimezoneOffset()+(Ya(this.g)?"&l=1":"")+"&_";this.da===g&&s(f,function(a){window.top.postMessage("cbqpush::"+a.join("::"),"*")});this.T||fa(a,this.Fa)}};function Z(a,b){return b!==d&&b!==""?"&"+a+"="+b:""}p.ua=function(){this.g.update("_cb_cp",this.aa,3600,j,",")};
function Db(a){var b=a.g.e("_cb_cp");a.g.remove("_cb_cp");return b?"&D="+b:""}function Eb(a){return a.b.subdomain?a.b.subdomain:q.location.host.replace(/^www\./,"")}
function Cb(a){var b=a.b,c=a.B,e=q.location,f=c.getUid&&c.getUid()||b.uid,h=b.videodomain||c.getHost&&c.getHost()||b.domain,h=encodeURIComponent("video@"+h),m="",y=a.va?"&b="+a.va:"",l;l=a.b.path;l=a.b.useSubDomains!==j&&l&&l.substr(0,1)==="/"?Eb(a)+l:l;var F=c.getSections&&c.getSections(),J=c.getAuthors&&c.getAuthors(),N=Ha(b,0,"sections"),Q=Ha(b,1,"authors"),F=F===d||b.videoPageGroups?N:"&g0="+F.join(","),J=J===d||b.videoPageGroups?Q:"&g1="+J.join(","),Q="",N=a.B.getVideoPath();if(a.xa===d)a.xa=
N;else if(N!=a.xa)Q=Z("D",a.aa),a.aa=ha(hb(a)),a.xa=N,a.na=0,a.ma=0,a.$a=0,a.Za=0;if(a.Fb||Q||a.da===g&&a.Bb===j)a.Fb=j,m=(jb(a)?"&v=":"&r=")+kb(a);a.$a+=a.na;a.na=0;a.Za+=a.ma;a.ma=0;Bb(a);var P=N="",S="",O="";if(!a.da===g||a.Eb===g)N="&_vi="+lb(a),P="&_vp="+encodeURIComponent(l),S="&_vh="+oa(Eb(a)),O="&_vdd="+encodeURIComponent(b.domain);l=!b.noCookies&&a.g.isSupported();var K=c.getStrategyName?c.getStrategyName():"";return(e.protocol||"http:")+"//"+b.pingServer+"/ping?h="+h+"&g="+f+"&p="+oa(c.getVideoPath())+
"&i="+oa(c.getTitle())+F+J+"&u="+a.P+"&t="+a.aa+"&x=0&y=0&V=45"+Z("VS",K)+(l?"&n="+a.Ia:"&nc=1")+y+m+Q+Z("_vd",c.getTotalDuration())+N+P+S+O}p.Da=function(){var a=Ab(this);if(this.Ra!=a)this.Ra=a,Bb(this),this.K()};function Bb(a){var b=a.ba;a.ba=Fb(a)===g?5E3:a.B.getState()===I?xb:15E3;if(b!=a.ba)b=a.ba,clearInterval(a.ga),a.ga=setInterval(t(a.K,a),b)}function Ab(a){return a.B.getState()+a.B.getAdPosition()}
function Fb(a){return a.B.getState()==="s2"||a.B.getAdPosition()!==""&&a.B.getViewAdPlayTime!==-1}p.Vb=function(){Fb(this)===g&&(this.na+=1,this.B.getContentType()===H&&(this.ma+=1))};p.Ic=function(){window.parent.postMessage("cbdata?","*")};
p.fc=function(a){if(a.source===window.parent){var b=a.data;if(a.data.indexOf("domain=")===0){this.Eb=g;var c={domain:g,path:g,title:g,referrer:g,internal:g,subdomain:g,token:g},e=this;s(b.split("&"),function(a){var a=a.split("="),b=a[0],a=a[1];c[b]&&(e.b[b]=decodeURIComponent(a))});ja(window,"message",this.ra);clearInterval(this.la);this.la=d;this.Bb=g;this.K()}}};p.terminate=function(){clearInterval(this.nb);clearInterval(this.la);clearInterval(this.V);ja(window,"message",this.ra);Y.W.terminate.call(this)};
p.ca=function(){Y.W.ca.call(this);this.Hb=this.a=this.ra=i};function $(a){this.a=a;this.f=g;this.d=j;this.c=v();this.ka=this.V=this.J=this.M=d;Gb(this,Hb(this));this.D()}p=$.prototype;p.D=function(){this.V=setInterval(r(this.Da,this),100);var a=this.a.getPlayerState();(a===1||a===2||a===0)&&this.C()};p.Da=function(){if(this.a.getPlayerState()===1)clearInterval(this.V),this.V=d,this.C()};p.G=function(){this.f=g};p.C=function(){if(!this.d)this.d=g};function Hb(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}
function Gb(a,b){ra("//gdata.youtube.com/feeds/api/videos/"+b+"?v=2&alt=json",t(function(a){if(b==Hb(this))this.ka=a?{id:b,title:a&&a.entry&&a.entry.title&&a.entry.title.$t||""}:{id:b,title:""}},a))}p.j=function(){return this.f&&!!this.ka};p.v=function(){return this.ka&&this.ka.id===Hb(this)?this.ka.title:""};p.i=function(){return Hb(this)||this.a.getVideoUrl()};p.o=function(){return H};p.k=o("");p.w=function(){var a=this.a.getDuration();return ka(a)?a*1E3:a};
p.h=function(){if(!this.d)return I;var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};p.p=function(){return this.a.getCurrentTime()};p.n=o(-1);p.u=function(){return"http://img.youtube.com/vi/"+Hb(this)+"/default.jpg"};p.r=k();p.m=k();p.z=function(){return isNaN(this.c)?0:qa(this.c)};p.s=n("M");p.l=n("J");p.t=o("YT");$.prototype.getStrategyName=$.prototype.t;$.prototype.isReady=$.prototype.j;$.prototype.getTitle=$.prototype.v;$.prototype.getVideoPath=$.prototype.i;
$.prototype.getContentType=$.prototype.o;$.prototype.getAdPosition=$.prototype.k;$.prototype.getTotalDuration=$.prototype.w;$.prototype.getState=$.prototype.h;$.prototype.getCurrentPlayTime=$.prototype.p;$.prototype.getBitrate=$.prototype.n;$.prototype.getThumbnailPath=$.prototype.u;$.prototype.getPlayerType=$.prototype.r;$.prototype.getAutoplayType=$.prototype.m;$.prototype.getViewStartTime=$.prototype.z;$.prototype.getSections=$.prototype.s;$.prototype.getAuthors=$.prototype.l;
$.verify=function(a){return ma(a.getDuration)&&ma(a.getVideoUrl)&&ma(a.getVideoEmbedCode)};function Ib(){q._cbv_strategies||(q._cbv_strategies=[]);q._cbv_strategies.push(W);q._cbv_strategies.push(T);q._cbv_strategies.push(R);q._cbv_strategies.push($);q._cbv_strategies.push(U);q._cbv_strategies.push(M);q._cbv_strategies.push(L);q._cbv_strategies.push(V);q._cbv_strategies.push(X);this.cb=[];this.b=q._sf_async_config||{};Fa("_cbv",t(this.gc,this));this.b[yb]!==j&&Jb()}
Ib.prototype.gc=function(a){if(aa(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){Kb();return}else if(b==="removePlayer"){Lb(this,a[1]);return}}Mb(this,a)};function Mb(a,b){var c=j;s(q._cbv_strategies,function(a){if(a.verify(b)===g)return c=a,j});c===j||Nb(a,b,c)}function Lb(a,b){var c=a.cb,e=q.pSUPERFLY_video,f=pa(c,function(a){return b===a});f!==-1&&c.splice(f,1);f=pa(e,function(a){return a.a===b});f!==-1&&e.splice(f,1)[0].ca()}
function Nb(a,b,c){var e=j;s(a.cb,function(a){if(b===a)return e=g,j});e||(c=new Y(b,c),q.pSUPERFLY_video.push(c),gb(c),a.cb.push(b))}
function Jb(){window.jwplayer&&window.jwplayer().onReady?window._cbv.push(window.jwplayer):window.flowplayer?window._cbv.push(window.flowplayer):window.brightcove?window._cbv.push(window.brightcove):window.kWidget?window.kWidget.addReadyCallback(function(a){window._cbv.push(document.getElementById(a))}):window.$pdk?window._cbv.push(window.$pdk):s(document.getElementsByTagName("video"),function(a){a.getAttribute("data-account")==i?window._cbv.push(a):window.videojs&&(a=window.videojs(a.getAttribute("id")))&&
window._cbv.push(a)})}function Kb(){function a(){function a(b){q._cbv.push(b.target)}var b=q.YT.Player;s(document.getElementsByTagName("iframe"),function(f){var h=f.src,m=h&&h.indexOf("www.youtube.com/embed/");h&&m>=0&&m<9&&new b(f,{events:{onReady:a}})})}if(q.YT&&q.YT.Player)a();else{var b=q.onYouTubeIframeAPIReady;q.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(q,arguments)}catch(c){}a()}}}};if(window.location==window.parent.location&&!q.pSUPERFLY){var Ob=new G;q.pSUPERFLY=Ob;G.prototype.virtualPage=G.prototype.Nc;G.prototype.activity=G.prototype.Ob;gb(Ob);var Pb=x.q(g);if(Pb){u(q,"message",Ka);var Qb;if(Qb=Pb.getItem("_cb_ip")){var Rb=q.location;Qb=!(!/^([^.]+[.])?chartbeat\.com$/.test(Rb.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Rb.pathname))}Qb&&Ja()}}q.pSUPERFLY_video||(q.pSUPERFLY_video=[]);new Ib;})();
